- README.md
In case you still need this ! :wave:
> fix headers

- README.md
- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
- scripts/gen.sh
Start to define syntax and semantics. This only goes as far as `$` but sets the scene for other subpaths to be added.
Add temporary warning about this not being ready for publication.
Also add a utility for generating HTML and text files from XML and for checking the XML and ABNF.
> Start to define syntax and semantics

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
See the [rendered HTML](https://glyn.github.io/internet-draft/) version of this PR.
> union slices

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
This allows slices of the form [0:10:].
> Allow step of array slice to be omitted

- .gitattributes
- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
- scripts/gen.sh
Related to #29 and jsonpath-standard/jsonpath-reference-implementation#22
@glyn
> Change array slicing specification

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
See also a [rendered version](https://glyn.github.io/internet-draft/#name-array-access-2).
> Gentle introduction to array access

- CONTRIBUTING.md
- README.md
Merge information from the previous README.
> Merge README information

- draft-ietf-jsonpath-base.md
Thanks to @cabo, I don't need to publicise my retirement quite so
starkly.
> Blank org for Glyn Normington

- .github/workflows/ghpages.yml
- .github/workflows/publish.yml
https://github.com/martinthomson/i-d-template/issues/273#issuecomment-859173896
> Try to avoid the "default branch" noise in builds

- draft-ietf-jsonpath-base.md
Here's a chance to actually have the discussion if anyone wants to.
> Close discussion D4

- draft-ietf-jsonpath-base.md
Here's a chance to actually have the discussion if anyone wants to.
> Close discussion D1

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/110
> Support arbitrary predicate structure

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/103
> Define partial determinism of ..

- TOOLS.md
> Create TOOLS.md from issue 82

- draft-ietf-jsonpath-base.md
> Need date update.

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/150
> Allow filters in list selectors

- draft-ietf-jsonpath-base.md
> updated table 1

- draft-ietf-jsonpath-base.md
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/136
> Filter and list inline examples

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/171
> Semantics of `null`

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/167
> Improve filter selector section

- draft-ietf-jsonpath-base.md
> Add content to Security Considerations section

- draft-ietf-jsonpath-base.md
> Remove confusing periods at the end of the list in §3.5 intro

- draft-ietf-jsonpath-base.md
See also [this rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/186-security-considerations/draft-ietf-jsonpath-base.html#name-attacks-on-security-mechani).
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/186
> Improve security considerations

- draft-ietf-jsonpath-base.md
See also [this rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/188-associativity/draft-ietf-jsonpath-base.html#name-semantics-9).
Ref: https://en.wikipedia.org/wiki/Boolean_algebra#Laws
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/188
> Logical operator semantics

- draft-ietf-jsonpath-base.md
Add array slicing, filters, and lists.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/219
> Add descendant selectors

- draft-ietf-jsonpath-base.md
Also add some general advice from https://www.rfc-editor.org/rfc/rfc8949#name-security-considerations.
See also [this rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/186-recursion-DOS/draft-ietf-jsonpath-base.html#name-attack-vectors-on-jsonpath-).
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/186#issuecomment-1158920404
> Mention recursion as an attack vector

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/208
> Move filter semantics out of syntax section

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/199
> Fold processing model into semantics section

- draft-ietf-jsonpath-base.md
I want to take the opportunity of there being no PRs in flight to make this purely editorial change to the order of the spec.
It avoids unnecessary forward references to the filter and list selectors.
> Move descendant selector section

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/229
> Clarify scope regarding invalid JSON

- draft-ietf-jsonpath-base.md
The inspiration of the example doesn't add much value.
> Drop reference to XML

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/236
Reviewers may find [this rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/236-structured-equality/draft-ietf-jsonpath-base.html#name-comparisons) useful.
> Equality and inequality of structured values

- draft-ietf-jsonpath-base.md
There were picked up by @goessner:
* Improve table 1
* Improve comparison examples
* Link to Boolean laws
* Make some examples shorter
* More list selector examples
* Compress two examples into one
* Clarify description of Normalized Paths
> More nit fixes

- draft-ietf-jsonpath-base.md
Fix a few nits noticed while skimming -06
> Post 06 nits

- draft-ietf-jsonpath-base.md
This PR replaces __APPENDER__ with segment. If merged, this will extend PR 263.
> Replace __APPENDER__ with segment

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/249
> Define > in terms of <

- draft-ietf-jsonpath-base.md
This PR is a series of changes which are submitted together since they would tread on each other's toes if submitted separately.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/252
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/260
> Issue fixes and editorial changes

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/285
> Delete unused and conflicting term

- draft-ietf-jsonpath-base.md
We expect to use this term in the description of extensions.
> Free up the term function

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/195
> Existence with non-singular paths

- draft-ietf-jsonpath-base.md
This is a stab at addressing one @cabo's review comments in PR #263.
> Improve overview structure

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/291
> Avoid duplicate id

- draft-ietf-jsonpath-base.md
The text will be adjusted in a future PR.
> Move JSON value text to its own, earlier section

- draft-ietf-jsonpath-base.md
This is a draft for us to contemplate and update to see if we can reach a satisfactory clarification.
> Clarify why members and member names do not have nodes

- draft-ietf-jsonpath-base.md
@cabo: thanks for spotting this!
> Fix non-determinism example

- draft-ietf-jsonpath-base.md
> No negative zero

- draft-ietf-jsonpath-base.md
> Enable the use of [Optional]Boolean functions without comparison

- draft-ietf-jsonpath-base.md
This PR also addresses https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/327.
> Define syntactic validity of function expressions

- draft-ietf-jsonpath-base.md
Signed-off-by: Tim Bray <tbray@textuality.com>
Nothing fancy here, just like the title says.
> Editorial nits

- draft-ietf-jsonpath-base.md
mention nested filter-selectors, disambiguate which current node is meant.
> Close #340

- draft-ietf-jsonpath-base.md
Add pair of surrogate escapes to note on string format.
> Close #272

- draft-ietf-jsonpath-base.md
Add the necessary internal references.
> Close #345

- draft-ietf-jsonpath-base.md
- scripts/test-abnf.out
> Selection cleanup

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/378
> Clarify numeric equality

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/377
> Clarify JSONPath expression syntax

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/383
> length should take an OptionalValue

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/392
> Define count(Nothing)

- draft-ietf-jsonpath-base.md
Fix a right margin incursion, as well.
> Close #400

- draft-ietf-jsonpath-base.md
Wouldn't mind if we could get these editorials merged quickly so the bulk of the other PRs shrinks a bit.
> Extract some changes in #410 that are unrelated to conversions

- draft-ietf-jsonpath-base.md
Thanks to @gregsdennis for spotting this.
> NodesType functions are not directly comparable

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/430xsx
> Prohibit function overloading

- draft-ietf-jsonpath-base.md
> Rewrite Function Well-typedness (Section 2.6.3) to be less clunky

- draft-ietf-jsonpath-base.md
> Don't capitalize Singular Query (except in Terminology Section)

- draft-ietf-jsonpath-base.md
This can be done in many different ways.
This PR values noise reduction over consistency.
Comments welcome.
> 442 unnumbered fixes

- draft-ietf-jsonpath-base.md
Cherry-picked from https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/454
> Improve example formatting

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/468
> Editorial improvements

- draft-ietf-jsonpath-base.md
...by adding a clarifying note.
> (editorial): Second attempt to close #470

- draft-ietf-jsonpath-base.md
> Remove unnecessary statements about being informative

- draft-ietf-jsonpath-base.md
> Update RFCXXX references and IETF as Change controller

- draft-ietf-jsonpath-base.md
> Bad hyphen

- draft-ietf-jsonpath-base.md
> Add example to 1.5 with empty result

- draft-ietf-jsonpath-base.md
> Explain the firewall between query errors and data mismatches

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/495
> Number all headings

- .gitignore
- sourcecode/abnf/jsonpath_collected_abnf
The collected ABNF was out of date. Also add extraneous sourcecode contents to .gitignore.
> Collect ABNF and improve .gitignore

- draft-ietf-jsonpath-base.md
@cburgmer do you think the reference should include an organisation?
> Add acknowledgement

- draft-ietf-jsonpath-base.md
> Media Type Change Controller is IETF, not IESG

- draft-ietf-jsonpath-base.md
The nits were raised by Lars Eggert as part of a GEN AD review.
> Fix some nits

- draft-ietf-jsonpath-base.md
Thanks to Roman Danyliw for prompting this improvement.
> Improve attack vector description

- draft-ietf-jsonpath-base.md
> RW-C-11: Existence: Complement "null" example by "false" example

- draft-ietf-jsonpath-base.md
> RW-C-1: Be more explicit about what these "exact values" are.
