- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
See [rendered HTML](https://glyn.github.io/internet-draft/) for ease of reading.
@remorhaz: following on from the discussion in https://github.com/cburgmer/json-path-comparison/issues/42, would you care to take a crack at the grammar for `dot-child-name`? If you are up for this, please send a PR to https://github.com/glyn/internet-draft/tree/dot-child.
> dot child matcher

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
Also define encoding of paths.
Also use JSON Path instead of JSONPath.
See [rendered HTML](https://glyn.github.io/internet-draft/) for ease of reading.
> union child and index matchers

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
Align ABNF comments.
Use the term Unicode characters rather than Unicode symbols for consistency.
(Also regenerate, which fills in for a missing generate at master.)
> Editorial changes

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
Fixes https://github.com/jsonpath-standard/internet-draft/issues/20
See the [rendered HTML](https://glyn.github.io/internet-draft/) version of this PR.
> Use "selector" instead of "matcher"

- docs/index.html
- draft-normington-jsonpath-latest.html
running `docker-gen.sh` now runs xml2rfc version `3.2.1`.
This PR just checks in the minor modifications in the output that this tool does since `3.1.1`, so that next PRs will have more meaningful diffs in the output
> Run scripts/docker-gen.sh

- scripts/Dockerfile
- scripts/gen.sh
thus avoding other types of sourcecode (such as pseudocode) to be validated by the ABNF checker.
aex is still needed because it reformats the content for bap somehow (didn't investigate).
> Use xpath to feed only abnf soucecode to aex and bap

- docs/index.html
- draft-normington-jsonpath-latest.html
- draft-normington-jsonpath-latest.md
- draft-normington-jsonpath-latest.txt
- draft-normington-jsonpath-latest.xml
Thanks for feedback from Daniel Parker and Carsten Bormann.
> Editorial improvements

- draft-ietf-jsonpath-base.md
I created a pull request so we have something concrete to discuss to close #66.
> Align (and simplify) terminology.

- draft-ietf-jsonpath-base.md
See discussion in #84.
To do: What exactly doesn't $..* stand for -- the table currently says "member values" (i.e., no array elements).  Is that true?
> Editorial: Remove term "data item"

- draft-ietf-jsonpath-base.md
Resolves #16
Also, I'm not sure what needs to be included in the PR as far as generated files go.  Any guidance would be helpful.
> removed dashes `-` as valid characters for dot-name selectors

- draft-ietf-jsonpath-base.md
* Generalise comparisons
* Make regex operator conform to Perl etc.
* Add operator precedence table
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/112
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/113
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/114
> Filter predicate improvements

- draft-ietf-jsonpath-base.md
> blank space added

- draft-ietf-jsonpath-base.md
Lots of niggly details re blank space.
Style consistency, some missing places (assuming we stick with the liberal approach).
Allowing "in" before or after a newline or tab.
Adding some legend to the only remaining table with XPath content in the main document.
> Various nits on #129, #131

- draft-ietf-jsonpath-base.md
XPath details are a distraction in the body of the spec.
In the future, readers are increasingly likely to come to this spec with no exposure to XPath or, for that matter, XML.
> Relegate XPath details to the appendix

- draft-ietf-jsonpath-base.md
From the meeting at IETF 112 ([1]):
**Consensus**: 'in' won't be used, but it will be easy to add later if there's real demand
[1] https://datatracker.ietf.org/doc/minutes-112-jsonpath/
> Delete the "in" operator

- draft-ietf-jsonpath-base.md
There does not seem to be an appetite for doing the necessary spec work. This PR will test that assertion.
Filter expressions are still supported, but not "container expressions", of the form [(...)].
> Delete expression language

- draft-ietf-jsonpath-base.md
Clarify related text; add explanation of change.
Take slice-selector apart to define slice-index.
Close #21.
> Rename "union selector" to "list selector"

- draft-ietf-jsonpath-base.md
Index expressions of the form [(...)] are not supported.
@.length, to obtain the length of an array, is not supported.
> Remove examples with invalid syntax

- draft-ietf-jsonpath-base.md
Specify Normalized Paths
Also clarify the relationship of JSONPath in general, and Normalized Paths in particular, to JSON Pointer.
The approach for Normal Paths is to minimise escaping. The alternative of maximising escaping was rejected because the results are unreadable. The alternative of escaping all but a particular set of characters was rejected because it would be biassed.
Co-authored-by: @cabo 
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/67
> Normalized Paths and how JSONPath relates to JSON Pointer

- draft-ietf-jsonpath-base.md
> Add proposal for handling regexps.

- draft-ietf-jsonpath-base.md
Introduce the term Singular Path.
Restrict paths in filter expressions to be Singular Paths so that,
for instance, existence tests and the left and right side of comparisons
do not involve more than one node.
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/155
> Singular paths

- draft-ietf-jsonpath-base.md
To do:
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/166
> Move list select after filter selector

- draft-ietf-jsonpath-base.md
Let's use this PR to hash out the formatting preferences. We can come back and tweak later, but please suggest any changes now before I replicate this format in other sections.
See the [rendered HTML](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/inline-examples-root/draft-ietf-jsonpath-base.html#name-root-selector) and the [rendered plain text](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/inline-examples-root/draft-ietf-jsonpath-base.txt).
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/136
> Inline examples (batch 1)

- draft-ietf-jsonpath-base.md
* Exclude the node itself
* Define the term "descendants" more precisely
* Define the descendant selector semantics more thoroughly
Fixes: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/177
> Descendant selector semantics

- draft-ietf-jsonpath-base.md
Per discussion at recent interim.
> String matching is codepoint by codepoint, no normalization

- draft-ietf-jsonpath-base.md
This is probably a bit too wordy, but is a starting point for a sharper definition of the nodelist orders which can be produced by the descendant selector.
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/215
> Sharpen up descendant ordering terminology

- draft-ietf-jsonpath-base.md
... instead of "JSON document" or "JSON value".
"JSON value" is retained in some contexts where it refers to specific
values i JSON rather than a whole document.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/210
> Use "JSON text" term

- draft-ietf-jsonpath-base.md
* Editorial improvements
* Correct != comparison involving at least one empty nodelist.
> Follow on to PR 214

- draft-ietf-jsonpath-base.md
And:
* allow normal string comparison.
* use some phrases consistently (editorial change only).
(Reviewers may like to view [this rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/comparison-improvements/draft-ietf-jsonpath-base.html#name-comparisons).)
The options under consideration in issue [212](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/212) were:
1. [The current draft as of 2022-07-22](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/blob/59b20529af450fc9d9a00179b95a6ae5bbe56de0/draft-ietf-jsonpath-base.md#comparisons).
2. [The option of making `<`, `>`, `<=`, and `>=` false when not comparing two numbers](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/212#issuecomment-1191676225).
3. [The NaB …
> Make all undesirable comparisons yield false

- draft-ietf-jsonpath-base.md
The deleted text referred, erroneously, to an example obtaining the
number of elements in an array. It also used the term "expression
mechanism" instead of "filter expression".
On the whole, it seemed better to slim the text down to the bare
minimum.
> Slim down the text before table 2

- draft-ietf-jsonpath-base.md
The one to one correspondence sentence gives us most of the desired
properties. The fact that for distinct Normalized Paths there will always
be at least one JSON value which can distinguish the paths is interesting
but not crucial. If it's confusing to some people, then it's probably
a distraction.
> Delete confusing language about Normalized Paths

- draft-ietf-jsonpath-base.md
Centralize the text that explains how non-interoperable JSON may cause unpredictable behavior.
This is a little clumsy as the sections to be referenced are currently unnumbered.
> Centralize non-JSON considerations

- draft-ietf-jsonpath-base.md
Also tweak the wording of the list semantics section.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/232
Reviewers may find the [rendered version](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/232-descendant-list-semantics/draft-ietf-jsonpath-base.html#name-semantics-10) useful.
> Define descendant list semantics

- draft-ietf-jsonpath-base.md
These went AWOL during the recent syntax rework.
> Reinstate child segment examples

- draft-ietf-jsonpath-base.md
Give an example to emphasise the spec behaviour. At the time of writing, this disagrees with the implementation consensus here:
https://cburgmer.github.io/json-path-comparison/results/union_with_keys_after_recursive_descent.html
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/265
> Ordering of descendant segment with multiple selectors

- draft-ietf-jsonpath-base.md
This is an attempt to make two sentences in the abstract and introduction less clunky while not jettisoning their precision.
> Improve abstract/intro wording

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/274
> Delete messy example

- draft-ietf-jsonpath-base.md
The deleted statement might be understood to mean that member names have nodes. But it's explicitly stated that member names are not values (and therefore they do not have nodes).
An alternative solution would be to qualify the deleted statement as follows, but this is very clunky in context:
> (but not its member names, which are not values and which do not have nodes)
> Delete confusing statement

- draft-ietf-jsonpath-base.md
JSON types are not used much in the JSON spec. It is debatable whether there really is a boolean type or simply the values `true` and `false`. Also, the JSONPath spec doesn't really benefit from this term.
> Avoid using JSON type terminology

- draft-ietf-jsonpath-base.md
Non-normative may be a better option, throughout, because surely normative sections are informative too?
@cabo WDYT?
> Use informative instead of non-normative?

- draft-ietf-jsonpath-base.md
Move the initial examples into the introduction since the purpose of the examples is introductory.
Mark certain sections as informative (rather than normative).
> Introduction tweaks

- draft-ietf-jsonpath-base.md
Specifically, use the nodelist term more consistently with elsewhere in the document.
> Editorial changes to semantics section

- draft-ietf-jsonpath-base.md
Generally, use "this document" rather than "this specification". Then use the term specification judiciously.
Prefer the term "language" to "platform".
> Consistently refer to "this document"; prefer "language" to "platform"

- draft-ietf-jsonpath-base.md
... so that they appear in the table of contents. More editorial polishing may be required afterward, but this gets a block move of some examples out of the way while there aren't many other PRs in flight.
> Promote function extensions

- draft-ietf-jsonpath-base.md
This is currently done inconsistently and doesn't add much value.
Instead, define terms in the Terminology section.
**Reviewers please note**: `_indexing_` is not modified. This avoids a clash with https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/314 which deletes the term.
> Avoid italicising terms

- draft-ietf-jsonpath-base.md
Avoid the term indexing, so we don't need to worry about whether it applies only to arrays or to arrays and objects.
> Clean up the term index

- draft-ietf-jsonpath-base.md
Add note that using the extension point mechanism doesn't imply the "function extensions" to be non-mandatory.
> Close #323

- draft-ietf-jsonpath-base.md
Remove single-valued type "Absent".
This is not useful as a function signature type (parameter or result).
> Close #342

- draft-ietf-jsonpath-base.md
clarify that filter expressions are side-effect free and therefore, short-circuiting does not make a difference
> Close #334

- draft-ietf-jsonpath-base.md
Delete the editor's note as
»Note that there is no deduplication of the nodelist.« is now the agreed behavior.
> Close #325

- draft-ietf-jsonpath-base.md
> `length()` function should return Nothing on invalid input

- draft-ietf-jsonpath-base.md
Resolves #360
Also, I noticed a minor read-flow issue and reorganized a paragraph to match the other section.
> `match()` and `search()` returns are not comparable

- draft-ietf-jsonpath-base.md
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/379
@cabo Any advice on how to format the table so that line length warnings are not produced (by `make` or `scripts/gen.sh`)?
> Update terminology in IANA Considerations

- draft-ietf-jsonpath-base.md
Resolves #366 
This is literally just a renaming of the names in the Type column of Table 13.
I also noticed that the `count()` description doesn't account for non-nodelist inputs.  I'll open another issue for that.
> added 'Type' to all type names to distinguish from abstractions

- draft-ietf-jsonpath-base.md
The typing is valid according to the validity rules for functions.
> Fix match example

- draft-ietf-jsonpath-base.md
General simplification and cleanup of the type system used in filter selectors.
Intended to supersede #402, which this is based on.
Intended to supersede #395.
Closes #387.
Closes #389.
Closes #401.
> Filter selector cleanup

- draft-ietf-jsonpath-base.md
There are some syntactical representations, e.g.:
* LogicalTrue can be represented by (1==1).
* LogicalFalse can be represented by (1==0).
* Nothing can be represented by a query that always returns the empty nodelist, such as $[?1==0].
But these are somewhat circuitous rather than direct.
See https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/403#discussion_r1122546568
> Sharpen up the absence of syntactical representations

- draft-ietf-jsonpath-base.md
Builds on #412.  Attempts to address [this comment](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/412#discussion_r1120934952) from @cabo:
> There are 16 combinations. 5 of them are explained. You need functions like exist() and value() to make a few more work.
Only valid/well-formed scenarios are explained; others are considered invalid/poorly-formed.
> Improve well typedness rules

- draft-ietf-jsonpath-base.md
This implicit conversion can be surprising in some situations, so it is made explicit via the value() function.
Calling the value() function is a conscious choice, so should not be a surprise to the user.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/404
> Avoid implicitly converting NodesType to ValueType

- draft-ietf-jsonpath-base.md
PR #424 changed the spec to use "path" only for paths, and "query" for queries. The term "JSONPath" is then left in need of some motivation. This is provided in the History section so as not to interfere with the normative text.
> Motivate the term "JSONPath"

- draft-ietf-jsonpath-base.md
The editorial suggestions are trying to be a bit more idiomatic and improve flow; my feelings will not be hurt by any rejections.
I'm not sure the spec quite covers index selectors of the form [5:] so I tried adding that. If I got it wrong, that may be a symptom of an editorial problem.
I think it's bad form to use the word "canonical" without saying what you mean, so I removed it from section 2.9.
> lightweight editorial suggestions and lose "canonical"

- draft-ietf-jsonpath-base.md
Also tidy up the well-typedness rules and add an example.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/427
> Avoid abstract type language

- draft-ietf-jsonpath-base.md
Also, delete a term which is used only in the definition of the next term.
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/440
> Editorial consistency improvements

- draft-ietf-jsonpath-base.md
Use parentheses as an indication that something is a function.
Also, don't confuse the reader by alluding to potential future alternatives to value().
Reviewers: is this an improvement? It's a draft PR for now until we decide the change is worthwhile.
> Improve function extension language

- draft-ietf-jsonpath-base.md
(See discussion over in https://github.com/ietf-wg-jsonpath/iregexp/pull/23 )
> Clarify that JSONPath queries are sequences of Unicode scalar values.

- draft-ietf-jsonpath-base.md
Section 1.3 covers this hazard. This should fix #473.
> JSON strings are unfortunately not sequences of scalar values.

- Makefile
Diff is dominated by ToC without this.
(Please merge and then merge into #482.)
> Reduce diff noise

- draft-ietf-jsonpath-base.md
> Expand `Nothing` to “special result `Nothing`” in a number of places

- draft-ietf-jsonpath-base.md
(Doesn't quite trigger the restatement anti-pattern)
> Repeat MUST in i.e.

- draft-ietf-jsonpath-base.md
Darrel Miller pointed out that the definition of S is not easy to find when reading the document sequentially.
> Define S near where it is first used

- Makefile
- draft-ietf-jsonpath-base.md
- scripts/gen.sh
- sourcecode/abnf/jsonpath_collected_abnf
- sourcecode/abnf/normalized_path_collected_abnf
We don't have to merge this, but this PR shows how to do it.
> Add an appendix with collected ABNF grammar

- draft-ietf-jsonpath-base.md
Make it clear that this is not required, unlike in the original JSONPath article. Also, avoid using such parentheses in examples for consistency.
> Clarify wrapping filter expressions in parentheses

- draft-ietf-jsonpath-base.md
> Rob Wilton #3: clarify "are not ordered" in filter examples

- draft-ietf-jsonpath-base.md
The specific case addressed here is about JSON values large enough so you no longer can evaluate, e.g., [?length(@) < length($.a)], in exact numbers. This is a bit of a luxury problem, as 2**53 bytes ⩰ 9 Petabytes. Backblaze reports they can [store a Petabyte for some $35000][1], so this is not an entirely hypothetical case any more, and will get less so during the time the spec lasts.
[1]: https://www.backblaze.com/blog/petabytes-on-a-budget-10-years-and-counting/
> Rob Wilton #1: clarify luxury overflow
